version: "3.0"

services:
  app:
    image: lovehyun/flask-eg:1.0
    ports:
      - "8000:5000"

  database:
    image: mysql:5.7
    ports:
      - "3333:3306"
    environment: 
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    volumes:
      - ./database:/var/lib/mysql
