# first stage build
FROM golang:alpine AS builder
ENV GO111MODULE=on CGO_ENABLE=0 GOOS=linux GOARCH=amd64

WORKDIR /build

COPY go.mod go.sum main.go ./
RUN go mod download
RUN go build -o main

WORKDIR /dist
RUN cp /build/main .

# second stage build
FROM alpine
COPY --from=builder /dist/main .

ENTRYPOINT ["./main"]
