version: '3'

services:
  db:
    image: mysql:5.7  # mysql:latest 도 무방
    volumes:
      - mysql_vol:/var/lib/mysql  # 볼륨 미사용시 ./mysql_data
    restart: always  # unless-stopped 를 권장
    environment: 
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_USER: $MYSQL_USER  # 사용자 계정 환경변수
      MYSQL_PASSWORD: $MYSQL_USER_PASSWORD  # 사용자 암호 환경변수
      MYSQL_DATABASE: wordpress  # DB 이름
    networks:
      - app-network  # 필요한 경우

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "80:80"
    restart: always  # unless-stopped 를 권장
    environment:
      WORDPRESS_DB_HOST: db:3306  # 기본포트라 그냥 db만 써주어도 무방
      WORDPRESS_DB_USER: $MYSQL_UESR  # 사용자 계정 환경변수
      WORDPRESS_DB_PASSWORD: $MYSQL_USER_PSSSWORD   # 사용자 암호 환경변수
      WORDPRESS_DB_NAME: wordpress  # DB 이름
    volumes:
      - wordpress_vol:/var/www/html  # 볼륨 미사용시 ./wordpress_data
      # - ./php/php.ini:/usr/local/etc/php/php.ini  # 필요한 경우
      # - ./upload.ini:/usr/local/etc/php/conf.d/uploads.ini  # 필요한 경우
    networks:
      - app-network  # 필요한 경우

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:latest
    env_file: .env
    environment: 
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    ports:
      - 8080:80

volumes:
  mysql_vol:
  wordpress_vol:

networks:
  app-network:
    driver: bridge
