# docker-compose up -d
# docker-compose logs -f
# curl localhost   (80번 포트 통해 3개의 컨테이너로 서비스 되는 것 확인)
version: '3'

services:
  my-web:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - my-flask1
      - my-flask2
      - my-flask3
  my-flask1:
    image: lovehyun/flask-app:1.3
    environment:
      - APP_COLOR=green
  my-flask2:
    image: lovehyun/flask-app:1.3
    environment:
      - APP_COLOR=orange
  my-flask3:
    image: lovehyun/flask-app:1.3
    environment:
      - APP_COLOR=red
